pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - head~=^update/
      - status-success=Build Success (ubuntu-latest, 2.13.5, adopt@1.8)
    actions:
      merge:
        method: rebase
        rebase_fallback: none
