
name: Scala Steward

on:
  schedule:
    - cron: '0 0 * * 0' # This workflow will launch at 00:00 every Sunday
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.STEWARD_TOKEN }}
          author-email: alessandro.zoffoli@gmail.com
